version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  groups:
    all-dependencies:
      patterns:
        - "*"
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
  groups:
    all-dependencies:
      patterns:
        - "*"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  groups:
    all-dependencies:
      patterns:
        - "*"